<?php

namespace ContainerI5yMtm4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Jzp2cBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Jzp2cB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Jzp2cB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\BlogController::delete' => ['privates', '.service_locator.nSj2Ri7.App\\Controller\\Admin\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\Admin\\BlogController::edit' => ['privates', '.service_locator.nSj2Ri7.App\\Controller\\Admin\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\Admin\\BlogController::index' => ['privates', '.service_locator.BwviCMx.App\\Controller\\Admin\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\Admin\\BlogController::new' => ['privates', '.service_locator.q60ydOj.App\\Controller\\Admin\\BlogController::new()', 'getBlogControllernewService', true],
            'App\\Controller\\Admin\\BlogController::show' => ['privates', '.service_locator.gOIcUNH.App\\Controller\\Admin\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\BlogController::commentForm' => ['privates', '.service_locator.gOIcUNH.App\\Controller\\BlogController::commentForm()', 'getBlogControllercommentFormService', true],
            'App\\Controller\\BlogController::commentNew' => ['privates', '.service_locator.qRZDSNw.App\\Controller\\BlogController::commentNew()', 'getBlogControllercommentNewService', true],
            'App\\Controller\\BlogController::index' => ['privates', '.service_locator.tgvAFsn.App\\Controller\\BlogController::index()', 'getBlogControllerindex2Service', true],
            'App\\Controller\\BlogController::postShow' => ['privates', '.service_locator.gOIcUNH.App\\Controller\\BlogController::postShow()', 'getBlogControllerpostShowService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.h4s2Zqm.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.Z5B5n2D.App\\Controller\\UserController::changePassword()', 'getUserControllerchangePasswordService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Controller\\Admin\\BlogController:delete' => ['privates', '.service_locator.nSj2Ri7.App\\Controller\\Admin\\BlogController::delete()', 'getBlogControllerdeleteService', true],
            'App\\Controller\\Admin\\BlogController:edit' => ['privates', '.service_locator.nSj2Ri7.App\\Controller\\Admin\\BlogController::edit()', 'getBlogControllereditService', true],
            'App\\Controller\\Admin\\BlogController:index' => ['privates', '.service_locator.BwviCMx.App\\Controller\\Admin\\BlogController::index()', 'getBlogControllerindexService', true],
            'App\\Controller\\Admin\\BlogController:new' => ['privates', '.service_locator.q60ydOj.App\\Controller\\Admin\\BlogController::new()', 'getBlogControllernewService', true],
            'App\\Controller\\Admin\\BlogController:show' => ['privates', '.service_locator.gOIcUNH.App\\Controller\\Admin\\BlogController::show()', 'getBlogControllershowService', true],
            'App\\Controller\\BlogController:commentForm' => ['privates', '.service_locator.gOIcUNH.App\\Controller\\BlogController::commentForm()', 'getBlogControllercommentFormService', true],
            'App\\Controller\\BlogController:commentNew' => ['privates', '.service_locator.qRZDSNw.App\\Controller\\BlogController::commentNew()', 'getBlogControllercommentNewService', true],
            'App\\Controller\\BlogController:index' => ['privates', '.service_locator.tgvAFsn.App\\Controller\\BlogController::index()', 'getBlogControllerindex2Service', true],
            'App\\Controller\\BlogController:postShow' => ['privates', '.service_locator.gOIcUNH.App\\Controller\\BlogController::postShow()', 'getBlogControllerpostShowService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.h4s2Zqm.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.Z5B5n2D.App\\Controller\\UserController::changePassword()', 'getUserControllerchangePasswordService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.q60ydOj.App\\Controller\\UserController::edit()', 'getUserControllereditService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
        ], [
            'App\\Controller\\Admin\\BlogController::delete' => '?',
            'App\\Controller\\Admin\\BlogController::edit' => '?',
            'App\\Controller\\Admin\\BlogController::index' => '?',
            'App\\Controller\\Admin\\BlogController::new' => '?',
            'App\\Controller\\Admin\\BlogController::show' => '?',
            'App\\Controller\\BlogController::commentForm' => '?',
            'App\\Controller\\BlogController::commentNew' => '?',
            'App\\Controller\\BlogController::index' => '?',
            'App\\Controller\\BlogController::postShow' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::changePassword' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\BlogController:delete' => '?',
            'App\\Controller\\Admin\\BlogController:edit' => '?',
            'App\\Controller\\Admin\\BlogController:index' => '?',
            'App\\Controller\\Admin\\BlogController:new' => '?',
            'App\\Controller\\Admin\\BlogController:show' => '?',
            'App\\Controller\\BlogController:commentForm' => '?',
            'App\\Controller\\BlogController:commentNew' => '?',
            'App\\Controller\\BlogController:index' => '?',
            'App\\Controller\\BlogController:postShow' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:changePassword' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
