<?php

namespace ContainerI5yMtm4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nSj2Ri7.App\Controller\Admin\BlogController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nSj2Ri7.App\\Controller\\Admin\\BlogController::edit()'] = ($container->privates['.service_locator.nSj2Ri7'] ?? $container->load('get_ServiceLocator_NSj2Ri7Service'))->withContext('App\\Controller\\Admin\\BlogController::edit()', $container);
    }
}
